version: 2.1

executors:
  default:
    working_directory: ~/bank_api_rails
    docker:
      - image: circleci/ruby:3.0.0
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLER_VERSION: 2.0.1
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          PG_HOST: 127.0.0.1
          PGUSER: hixonrails
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_DB: bank_api_rails_test
          POSTGRES_USER: hixonrails
          PORTS: 5430


commands:
  configure_bundler:
    description: Configure bundler
    steps:
      - run:
          name: Configure bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - bank_api_rails-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - bank_api_rails-
      - configure_bundler
      - run:
          name: Install bundle
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 2m

      - run:
          name: Restart Postgres
          command: sudo systemctl status postgresql

      - run:
          name: Setup DB
          command: bundle exec rails db:drop db:create db:schema:load --trace DISABLE_DATABASE_ENVIRONMENT_CHECK=1 
      - run:
          name: Run rspec
          command: bundle exec rspec spec

      - store_artifacts:
          path: coverage
      - save_cache:
          key: bank_api_rails-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/
          paths:
            - ./bank_api_rails

workflows:
  version: 2
  integration:
    jobs:
      - build
